---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  

platforms:
  - name: ubuntu-14.04
    driver_config:



suites:
  - name: default
    provisioner:
      client_rb:
        environment: allocation-development

    run_list:
      - recipe[mynginx::default]

    attributes:
